In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [2]:
df = pd.read_csv('F:/Thinkful/Files/table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.csv')

In [3]:
df

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NEW YORK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Offenses Known to Law Enforcement,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"by City, 2013",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3,NaN
4,Adams Village,"1,861",0,0,NaN,0,0,0,12,2,10,0,0,NaN
5,Addison Town and Village,"2,577",3,0,NaN,0,0,3,24,3,20,1,0,NaN
6,Akron Village,"2,846",3,0,NaN,0,0,3,16,1,15,0,0,NaN
7,Albany,"97,956",791,8,NaN,30,227,526,"4,090",705,"3,243",142,NaN,NaN
8,Albion Village,"6,388",23,0,NaN,3,4,16,223,53,165,5,NaN,NaN
9,Alfred Village,"4,089",5,0,NaN,0,3,2,46,10,36,0,NaN,NaN
10,Allegany Village,"1,781",3,0,NaN,0,0,3,10,0,10,0,0,NaN
11,Amherst Town,"118,296",107,1,NaN,7,31,68,"2,118",204,"1,882",32,3,NaN
12,Amityville Village,"9,519",9,0,NaN,2,4,3,210,16,188,6,1,NaN
13,Amsterdam,"18,182",30,0,NaN,0,12,18,405,99,291,15,0,NaN
14,Arcade Village,"2,053",0,0,NaN,0,0,0,39,3,35,1,0,NaN
15,Ardsley Village,"4,523",5,0,NaN,0,3,2,33,4,28,1,0,NaN
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0,NaN
17,Attica Village,"2,522",2,0,NaN,0,0,2,5,0,4,1,0,NaN
18,Auburn,"27,270",96,1,NaN,20,22,53,859,132,721,6,NaN,NaN
19,Avon Village,"3,333",1,0,NaN,0,1,0,25,3,20,2,NaN,NaN
20,Baldwinsville Village,"7,473",5,0,NaN,0,1,4,88,10,77,1,0,NaN
21,Ballston Spa Village,"5,418",8,0,NaN,0,3,5,94,16,78,0,1,NaN
22,Batavia,"15,374",57,0,NaN,7,13,37,559,103,454,2,NaN,NaN
23,Bath Village,"5,733",15,0,NaN,1,3,11,191,32,157,2,2,NaN
24,Bedford Town,"17,627",5,0,NaN,0,1,4,156,26,127,3,NaN,NaN
25,Bethlehem Town,"34,243",13,0,NaN,0,3,10,442,50,388,4,NaN,NaN
26,Binghamton,"46,304",284,3,NaN,19,101,161,"2,349",525,"1,767",57,NaN,NaN
27,Black River,"1,410",0,0,NaN,0,0,0,14,2,12,0,0,NaN
28,Blooming Grove Town,"12,001",8,0,NaN,1,0,7,99,20,72,7,NaN,NaN
29,Bolivar Village,"1,022",1,0,NaN,0,0,1,4,2,2,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,"61,686",361,7,NaN,27,102,225,"2,528",449,"1,997",82,NaN,NaN
326,Vestal Town,"27,980",16,0,NaN,2,6,8,571,39,523,9,NaN,NaN
327,Walden Village,"6,887",18,1,NaN,2,1,14,142,13,124,5,NaN,NaN
328,Wallkill Town,"27,940",40,0,NaN,3,16,21,767,91,650,26,1,NaN
329,Walton Village,"3,012",6,0,NaN,1,0,5,68,18,50,0,NaN,NaN
330,Warsaw Village,"3,453",6,0,NaN,1,0,5,78,5,73,0,0,NaN
331,Washingtonville Village,"5,828",2,0,NaN,0,1,1,58,5,51,2,0,NaN
332,Waterford Town and Village,"8,392",4,0,NaN,0,0,4,59,6,52,1,0,NaN
333,Waterloo Village,"5,175",11,0,NaN,0,3,8,194,23,169,2,NaN,NaN
334,Watertown,"28,179",109,0,NaN,12,16,81,"1,165",169,953,43,NaN,NaN
335,Watervliet,"10,245",26,1,NaN,3,11,11,242,58,163,21,NaN,NaN
336,Watkins Glen Village,"1,862",6,0,NaN,0,0,6,92,10,80,2,NaN,NaN
337,Waverly Village,"4,337",5,0,NaN,0,1,4,54,9,41,4,NaN,NaN
338,Webster Town and Village,"43,777",21,0,NaN,2,3,16,469,101,361,7,NaN,NaN
339,Weedsport Village,"1,797",0,0,NaN,0,0,0,25,5,20,0,0,NaN
340,Wellsville Village,"4,574",11,0,NaN,1,0,10,164,32,129,3,1,NaN
341,Westhampton Beach Village,"1,732",2,0,NaN,0,0,2,44,4,37,3,0,NaN
342,West Seneca Town,"44,821",35,1,NaN,1,9,24,896,166,710,20,0,NaN
343,Whitehall Village,"2,604",6,0,NaN,0,0,6,62,12,49,1,NaN,NaN
344,White Plains,"57,559",78,1,NaN,3,28,46,"1,232",77,"1,134",21,NaN,NaN
345,Whitesboro Village,"3,733",4,0,NaN,0,0,4,36,14,21,1,0,NaN
346,Whitestown Town,"9,141",0,0,NaN,0,0,0,77,13,61,3,0,NaN
347,Woodbury Town,"10,685",3,0,NaN,0,2,1,541,9,529,3,NaN,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0,NaN
349,Woodstock Town,"5,931",2,0,NaN,0,0,2,58,13,45,0,NaN,NaN
350,Yonkers,"199,134","1,036",6,NaN,25,390,615,"2,368",470,"1,662",236,10,NaN
351,Yorktown Town,"36,643",15,0,NaN,0,2,13,334,45,287,2,NaN,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df.drop([0,1,2], axis=0)

In [5]:
df

,Table 8,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
3,City,Population,Violent\ncrime,Murder and\nnonnegligent\nmanslaughter,Rape\n(revised\ndefinition)1,Rape\n(legacy\ndefinition)2,Robbery,Aggravated\nassault,Property\ncrime,Burglary,Larceny-\ntheft,Motor\nvehicle\ntheft,Arson3,NaN
4,Adams Village,"1,861",0,0,NaN,0,0,0,12,2,10,0,0,NaN
5,Addison Town and Village,"2,577",3,0,NaN,0,0,3,24,3,20,1,0,NaN
6,Akron Village,"2,846",3,0,NaN,0,0,3,16,1,15,0,0,NaN
7,Albany,"97,956",791,8,NaN,30,227,526,"4,090",705,"3,243",142,NaN,NaN
8,Albion Village,"6,388",23,0,NaN,3,4,16,223,53,165,5,NaN,NaN
9,Alfred Village,"4,089",5,0,NaN,0,3,2,46,10,36,0,NaN,NaN
10,Allegany Village,"1,781",3,0,NaN,0,0,3,10,0,10,0,0,NaN
11,Amherst Town,"118,296",107,1,NaN,7,31,68,"2,118",204,"1,882",32,3,NaN
12,Amityville Village,"9,519",9,0,NaN,2,4,3,210,16,188,6,1,NaN
13,Amsterdam,"18,182",30,0,NaN,0,12,18,405,99,291,15,0,NaN
14,Arcade Village,"2,053",0,0,NaN,0,0,0,39,3,35,1,0,NaN
15,Ardsley Village,"4,523",5,0,NaN,0,3,2,33,4,28,1,0,NaN
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0,NaN
17,Attica Village,"2,522",2,0,NaN,0,0,2,5,0,4,1,0,NaN
18,Auburn,"27,270",96,1,NaN,20,22,53,859,132,721,6,NaN,NaN
19,Avon Village,"3,333",1,0,NaN,0,1,0,25,3,20,2,NaN,NaN
20,Baldwinsville Village,"7,473",5,0,NaN,0,1,4,88,10,77,1,0,NaN
21,Ballston Spa Village,"5,418",8,0,NaN,0,3,5,94,16,78,0,1,NaN
22,Batavia,"15,374",57,0,NaN,7,13,37,559,103,454,2,NaN,NaN
23,Bath Village,"5,733",15,0,NaN,1,3,11,191,32,157,2,2,NaN
24,Bedford Town,"17,627",5,0,NaN,0,1,4,156,26,127,3,NaN,NaN
25,Bethlehem Town,"34,243",13,0,NaN,0,3,10,442,50,388,4,NaN,NaN
26,Binghamton,"46,304",284,3,NaN,19,101,161,"2,349",525,"1,767",57,NaN,NaN
27,Black River,"1,410",0,0,NaN,0,0,0,14,2,12,0,0,NaN
28,Blooming Grove Town,"12,001",8,0,NaN,1,0,7,99,20,72,7,NaN,NaN
29,Bolivar Village,"1,022",1,0,NaN,0,0,1,4,2,2,0,0,NaN
30,Bolton Town,"2,325",2,0,NaN,0,0,2,24,4,20,0,0,NaN
31,Boonville Village,"2,054",1,0,NaN,0,0,1,20,6,14,0,0,NaN
32,Brant Town,"2,065",4,0,NaN,0,1,3,31,9,20,2,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,"61,686",361,7,NaN,27,102,225,"2,528",449,"1,997",82,NaN,NaN
326,Vestal Town,"27,980",16,0,NaN,2,6,8,571,39,523,9,NaN,NaN
327,Walden Village,"6,887",18,1,NaN,2,1,14,142,13,124,5,NaN,NaN
328,Wallkill Town,"27,940",40,0,NaN,3,16,21,767,91,650,26,1,NaN
329,Walton Village,"3,012",6,0,NaN,1,0,5,68,18,50,0,NaN,NaN
330,Warsaw Village,"3,453",6,0,NaN,1,0,5,78,5,73,0,0,NaN
331,Washingtonville Village,"5,828",2,0,NaN,0,1,1,58,5,51,2,0,NaN
332,Waterford Town and Village,"8,392",4,0,NaN,0,0,4,59,6,52,1,0,NaN
333,Waterloo Village,"5,175",11,0,NaN,0,3,8,194,23,169,2,NaN,NaN
334,Watertown,"28,179",109,0,NaN,12,16,81,"1,165",169,953,43,NaN,NaN
335,Watervliet,"10,245",26,1,NaN,3,11,11,242,58,163,21,NaN,NaN
336,Watkins Glen Village,"1,862",6,0,NaN,0,0,6,92,10,80,2,NaN,NaN
337,Waverly Village,"4,337",5,0,NaN,0,1,4,54,9,41,4,NaN,NaN
338,Webster Town and Village,"43,777",21,0,NaN,2,3,16,469,101,361,7,NaN,NaN
339,Weedsport Village,"1,797",0,0,NaN,0,0,0,25,5,20,0,0,NaN
340,Wellsville Village,"4,574",11,0,NaN,1,0,10,164,32,129,3,1,NaN
341,Westhampton Beach Village,"1,732",2,0,NaN,0,0,2,44,4,37,3,0,NaN
342,West Seneca Town,"44,821",35,1,NaN,1,9,24,896,166,710,20,0,NaN
343,Whitehall Village,"2,604",6,0,NaN,0,0,6,62,12,49,1,NaN,NaN
344,White Plains,"57,559",78,1,NaN,3,28,46,"1,232",77,"1,134",21,NaN,NaN
345,Whitesboro Village,"3,733",4,0,NaN,0,0,4,36,14,21,1,0,NaN
346,Whitestown Town,"9,141",0,0,NaN,0,0,0,77,13,61,3,0,NaN
347,Woodbury Town,"10,685",3,0,NaN,0,2,1,541,9,529,3,NaN,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0,NaN
349,Woodstock Town,"5,931",2,0,NaN,0,0,2,58,13,45,0,NaN,NaN
350,Yonkers,"199,134","1,036",6,NaN,25,390,615,"2,368",470,"1,662",236,10,NaN
351,Yorktown Town,"36,643",15,0,NaN,0,2,13,334,45,287,2,NaN,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.columns = ['City','Population','Violent\ncrime','Murder and\nnonnegligent\nmanslaughter',
              'Rape\n(revised\ndefinition)1','Rape\n(legacy\ndefinition)2','Robbery',
              'Aggravated\nassault','Property\ncrime','Burglary','Larceny-\ntheft',
              'Motor\nvehicle\ntheft','Arson3','extra']

In [7]:
df = df.drop(['extra'],axis = 1)

In [8]:
df = df.reset_index()

In [11]:
df = df.drop(['index'],axis = 1)
df = df.drop([0], axis = 0)

In [12]:
df

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
1,Adams Village,"1,861",0,0,NaN,0,0,0,12,2,10,0,0
2,Addison Town and Village,"2,577",3,0,NaN,0,0,3,24,3,20,1,0
3,Akron Village,"2,846",3,0,NaN,0,0,3,16,1,15,0,0
4,Albany,"97,956",791,8,NaN,30,227,526,"4,090",705,"3,243",142,NaN
5,Albion Village,"6,388",23,0,NaN,3,4,16,223,53,165,5,NaN
6,Alfred Village,"4,089",5,0,NaN,0,3,2,46,10,36,0,NaN
7,Allegany Village,"1,781",3,0,NaN,0,0,3,10,0,10,0,0
8,Amherst Town,"118,296",107,1,NaN,7,31,68,"2,118",204,"1,882",32,3
9,Amityville Village,"9,519",9,0,NaN,2,4,3,210,16,188,6,1
10,Amsterdam,"18,182",30,0,NaN,0,12,18,405,99,291,15,0
11,Arcade Village,"2,053",0,0,NaN,0,0,0,39,3,35,1,0
12,Ardsley Village,"4,523",5,0,NaN,0,3,2,33,4,28,1,0
13,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
14,Attica Village,"2,522",2,0,NaN,0,0,2,5,0,4,1,0
15,Auburn,"27,270",96,1,NaN,20,22,53,859,132,721,6,NaN
16,Avon Village,"3,333",1,0,NaN,0,1,0,25,3,20,2,NaN
17,Baldwinsville Village,"7,473",5,0,NaN,0,1,4,88,10,77,1,0
18,Ballston Spa Village,"5,418",8,0,NaN,0,3,5,94,16,78,0,1
19,Batavia,"15,374",57,0,NaN,7,13,37,559,103,454,2,NaN
20,Bath Village,"5,733",15,0,NaN,1,3,11,191,32,157,2,2
21,Bedford Town,"17,627",5,0,NaN,0,1,4,156,26,127,3,NaN
22,Bethlehem Town,"34,243",13,0,NaN,0,3,10,442,50,388,4,NaN
23,Binghamton,"46,304",284,3,NaN,19,101,161,"2,349",525,"1,767",57,NaN
24,Black River,"1,410",0,0,NaN,0,0,0,14,2,12,0,0
25,Blooming Grove Town,"12,001",8,0,NaN,1,0,7,99,20,72,7,NaN
26,Bolivar Village,"1,022",1,0,NaN,0,0,1,4,2,2,0,0
27,Bolton Town,"2,325",2,0,NaN,0,0,2,24,4,20,0,0
28,Boonville Village,"2,054",1,0,NaN,0,0,1,20,6,14,0,0
29,Brant Town,"2,065",4,0,NaN,0,1,3,31,9,20,2,0
30,Brewster,"2,358",0,0,NaN,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Utica,"61,686",361,7,NaN,27,102,225,"2,528",449,"1,997",82,NaN
323,Vestal Town,"27,980",16,0,NaN,2,6,8,571,39,523,9,NaN
324,Walden Village,"6,887",18,1,NaN,2,1,14,142,13,124,5,NaN
325,Wallkill Town,"27,940",40,0,NaN,3,16,21,767,91,650,26,1
326,Walton Village,"3,012",6,0,NaN,1,0,5,68,18,50,0,NaN
327,Warsaw Village,"3,453",6,0,NaN,1,0,5,78,5,73,0,0
328,Washingtonville Village,"5,828",2,0,NaN,0,1,1,58,5,51,2,0
329,Waterford Town and Village,"8,392",4,0,NaN,0,0,4,59,6,52,1,0
330,Waterloo Village,"5,175",11,0,NaN,0,3,8,194,23,169,2,NaN
331,Watertown,"28,179",109,0,NaN,12,16,81,"1,165",169,953,43,NaN
332,Watervliet,"10,245",26,1,NaN,3,11,11,242,58,163,21,NaN
333,Watkins Glen Village,"1,862",6,0,NaN,0,0,6,92,10,80,2,NaN
334,Waverly Village,"4,337",5,0,NaN,0,1,4,54,9,41,4,NaN
335,Webster Town and Village,"43,777",21,0,NaN,2,3,16,469,101,361,7,NaN
336,Weedsport Village,"1,797",0,0,NaN,0,0,0,25,5,20,0,0
337,Wellsville Village,"4,574",11,0,NaN,1,0,10,164,32,129,3,1
338,Westhampton Beach Village,"1,732",2,0,NaN,0,0,2,44,4,37,3,0
339,West Seneca Town,"44,821",35,1,NaN,1,9,24,896,166,710,20,0
340,Whitehall Village,"2,604",6,0,NaN,0,0,6,62,12,49,1,NaN
341,White Plains,"57,559",78,1,NaN,3,28,46,"1,232",77,"1,134",21,NaN
342,Whitesboro Village,"3,733",4,0,NaN,0,0,4,36,14,21,1,0
343,Whitestown Town,"9,141",0,0,NaN,0,0,0,77,13,61,3,0
344,Woodbury Town,"10,685",3,0,NaN,0,2,1,541,9,529,3,NaN
345,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
346,Woodstock Town,"5,931",2,0,NaN,0,0,2,58,13,45,0,NaN
347,Yonkers,"199,134","1,036",6,NaN,25,390,615,"2,368",470,"1,662",236,10
348,Yorktown Town,"36,643",15,0,NaN,0,2,13,334,45,287,2,NaN
349,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
type(df.loc[1][2])

str

In [21]:
for column in df:
    df[column] = df[column].str.replace(',', '')

In [22]:
df

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
1,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
2,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
3,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
4,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
5,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
6,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
7,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
8,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
9,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
10,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
11,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
12,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
13,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
14,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
15,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
16,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
17,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
18,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
19,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
20,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
21,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
22,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
23,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
24,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
25,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
26,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
27,Bolton Town,2325,2,0,NaN,0,0,2,24,4,20,0,0
28,Boonville Village,2054,1,0,NaN,0,0,1,20,6,14,0,0
29,Brant Town,2065,4,0,NaN,0,1,3,31,9,20,2,0
30,Brewster,2358,0,0,NaN,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
323,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
324,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
325,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
326,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
327,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
328,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
329,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
330,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
331,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
332,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
333,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
334,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
335,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
336,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
337,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
338,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
339,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
340,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
341,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
342,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
343,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
344,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
345,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
346,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
347,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
348,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
349,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
names = ['Population','Violent\ncrime','Murder and\nnonnegligent\nmanslaughter',
              'Rape\n(revised\ndefinition)1','Rape\n(legacy\ndefinition)2','Robbery',
              'Aggravated\nassault','Property\ncrime','Burglary','Larceny-\ntheft',
              'Motor\nvehicle\ntheft','Arson3']

In [28]:
for name in names:
    df[name] = pd.to_numeric(df[name])

In [29]:
type(df.loc[1][1])

numpy.float64

In [30]:
df

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
1,Adams Village,1861.0,0.0,0.0,NaN,0.0,0.0,0.0,12.0,2.0,10.0,0.0,0.0
2,Addison Town and Village,2577.0,3.0,0.0,NaN,0.0,0.0,3.0,24.0,3.0,20.0,1.0,0.0
3,Akron Village,2846.0,3.0,0.0,NaN,0.0,0.0,3.0,16.0,1.0,15.0,0.0,0.0
4,Albany,97956.0,791.0,8.0,NaN,30.0,227.0,526.0,4090.0,705.0,3243.0,142.0,NaN
5,Albion Village,6388.0,23.0,0.0,NaN,3.0,4.0,16.0,223.0,53.0,165.0,5.0,NaN
6,Alfred Village,4089.0,5.0,0.0,NaN,0.0,3.0,2.0,46.0,10.0,36.0,0.0,NaN
7,Allegany Village,1781.0,3.0,0.0,NaN,0.0,0.0,3.0,10.0,0.0,10.0,0.0,0.0
8,Amherst Town,118296.0,107.0,1.0,NaN,7.0,31.0,68.0,2118.0,204.0,1882.0,32.0,3.0
9,Amityville Village,9519.0,9.0,0.0,NaN,2.0,4.0,3.0,210.0,16.0,188.0,6.0,1.0
10,Amsterdam,18182.0,30.0,0.0,NaN,0.0,12.0,18.0,405.0,99.0,291.0,15.0,0.0
11,Arcade Village,2053.0,0.0,0.0,NaN,0.0,0.0,0.0,39.0,3.0,35.0,1.0,0.0
12,Ardsley Village,4523.0,5.0,0.0,NaN,0.0,3.0,2.0,33.0,4.0,28.0,1.0,0.0
13,Asharoken Village,658.0,0.0,0.0,NaN,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0
14,Attica Village,2522.0,2.0,0.0,NaN,0.0,0.0,2.0,5.0,0.0,4.0,1.0,0.0
15,Auburn,27270.0,96.0,1.0,NaN,20.0,22.0,53.0,859.0,132.0,721.0,6.0,NaN
16,Avon Village,3333.0,1.0,0.0,NaN,0.0,1.0,0.0,25.0,3.0,20.0,2.0,NaN
17,Baldwinsville Village,7473.0,5.0,0.0,NaN,0.0,1.0,4.0,88.0,10.0,77.0,1.0,0.0
18,Ballston Spa Village,5418.0,8.0,0.0,NaN,0.0,3.0,5.0,94.0,16.0,78.0,0.0,1.0
19,Batavia,15374.0,57.0,0.0,NaN,7.0,13.0,37.0,559.0,103.0,454.0,2.0,NaN
20,Bath Village,5733.0,15.0,0.0,NaN,1.0,3.0,11.0,191.0,32.0,157.0,2.0,2.0
21,Bedford Town,17627.0,5.0,0.0,NaN,0.0,1.0,4.0,156.0,26.0,127.0,3.0,NaN
22,Bethlehem Town,34243.0,13.0,0.0,NaN,0.0,3.0,10.0,442.0,50.0,388.0,4.0,NaN
23,Binghamton,46304.0,284.0,3.0,NaN,19.0,101.0,161.0,2349.0,525.0,1767.0,57.0,NaN
24,Black River,1410.0,0.0,0.0,NaN,0.0,0.0,0.0,14.0,2.0,12.0,0.0,0.0
25,Blooming Grove Town,12001.0,8.0,0.0,NaN,1.0,0.0,7.0,99.0,20.0,72.0,7.0,NaN
26,Bolivar Village,1022.0,1.0,0.0,NaN,0.0,0.0,1.0,4.0,2.0,2.0,0.0,0.0
27,Bolton Town,2325.0,2.0,0.0,NaN,0.0,0.0,2.0,24.0,4.0,20.0,0.0,0.0
28,Boonville Village,2054.0,1.0,0.0,NaN,0.0,0.0,1.0,20.0,6.0,14.0,0.0,0.0
29,Brant Town,2065.0,4.0,0.0,NaN,0.0,1.0,3.0,31.0,9.0,20.0,2.0,0.0
30,Brewster,2358.0,0.0,0.0,NaN,0.0,0.0,0.0,13.0,3.0,10.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,Utica,61686.0,361.0,7.0,NaN,27.0,102.0,225.0,2528.0,449.0,1997.0,82.0,NaN
323,Vestal Town,27980.0,16.0,0.0,NaN,2.0,6.0,8.0,571.0,39.0,523.0,9.0,NaN
324,Walden Village,6887.0,18.0,1.0,NaN,2.0,1.0,14.0,142.0,13.0,124.0,5.0,NaN
325,Wallkill Town,27940.0,40.0,0.0,NaN,3.0,16.0,21.0,767.0,91.0,650.0,26.0,1.0
326,Walton Village,3012.0,6.0,0.0,NaN,1.0,0.0,5.0,68.0,18.0,50.0,0.0,NaN
327,Warsaw Village,3453.0,6.0,0.0,NaN,1.0,0.0,5.0,78.0,5.0,73.0,0.0,0.0
328,Washingtonville Village,5828.0,2.0,0.0,NaN,0.0,1.0,1.0,58.0,5.0,51.0,2.0,0.0
329,Waterford Town and Village,8392.0,4.0,0.0,NaN,0.0,0.0,4.0,59.0,6.0,52.0,1.0,0.0
330,Waterloo Village,5175.0,11.0,0.0,NaN,0.0,3.0,8.0,194.0,23.0,169.0,2.0,NaN
331,Watertown,28179.0,109.0,0.0,NaN,12.0,16.0,81.0,1165.0,169.0,953.0,43.0,NaN
332,Watervliet,10245.0,26.0,1.0,NaN,3.0,11.0,11.0,242.0,58.0,163.0,21.0,NaN
333,Watkins Glen Village,1862.0,6.0,0.0,NaN,0.0,0.0,6.0,92.0,10.0,80.0,2.0,NaN
334,Waverly Village,4337.0,5.0,0.0,NaN,0.0,1.0,4.0,54.0,9.0,41.0,4.0,NaN
335,Webster Town and Village,43777.0,21.0,0.0,NaN,2.0,3.0,16.0,469.0,101.0,361.0,7.0,NaN
336,Weedsport Village,1797.0,0.0,0.0,NaN,0.0,0.0,0.0,25.0,5.0,20.0,0.0,0.0
337,Wellsville Village,4574.0,11.0,0.0,NaN,1.0,0.0,10.0,164.0,32.0,129.0,3.0,1.0
338,Westhampton Beach Village,1732.0,2.0,0.0,NaN,0.0,0.0,2.0,44.0,4.0,37.0,3.0,0.0
339,West Seneca Town,44821.0,35.0,1.0,NaN,1.0,9.0,24.0,896.0,166.0,710.0,20.0,0.0
340,Whitehall Village,2604.0,6.0,0.0,NaN,0.0,0.0,6.0,62.0,12.0,49.0,1.0,NaN
341,White Plains,57559.0,78.0,1.0,NaN,3.0,28.0,46.0,1232.0,77.0,1134.0,21.0,NaN
342,Whitesboro Village,3733.0,4.0,0.0,NaN,0.0,0.0,4.0,36.0,14.0,21.0,1.0,0.0
343,Whitestown Town,9141.0,0.0,0.0,NaN,0.0,0.0,0.0,77.0,13.0,61.0,3.0,0.0
344,Woodbury Town,10685.0,3.0,0.0,NaN,0.0,2.0,1.0,541.0,9.0,529.0,3.0,NaN
345,Woodridge Village,829.0,7.0,0.0,NaN,0.0,0.0,7.0,17.0,8.0,9.0,0.0,0.0
346,Woodstock Town,5931.0,2.0,0.0,NaN,0.0,0.0,2.0,58.0,13.0,45.0,0.0,NaN
347,Yonkers,199134.0,1036.0,6.0,NaN,25.0,390.0,615.0,2368.0,470.0,1662.0,236.0,10.0
348,Yorktown Town,36643.0,15.0,0.0,NaN,0.0,2.0,13.0,334.0,45.0,287.0,2.0,NaN
349,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
351,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df['Population2'] = df['Population'] ** 2

In [33]:
df.head()

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3,Population2
1,Adams Village,1861.0,0.0,0.0,NaN,0.0,0.0,0.0,12.0,2.0,10.0,0.0,0.0,3.463321e+06
2,Addison Town and Village,2577.0,3.0,0.0,NaN,0.0,0.0,3.0,24.0,3.0,20.0,1.0,0.0,6.640929e+06
3,Akron Village,2846.0,3.0,0.0,NaN,0.0,0.0,3.0,16.0,1.0,15.0,0.0,0.0,8.099716e+06
4,Albany,97956.0,791.0,8.0,NaN,30.0,227.0,526.0,4090.0,705.0,3243.0,142.0,NaN,9.595378e+09
5,Albion Village,6388.0,23.0,0.0,NaN,3.0,4.0,16.0,223.0,53.0,165.0,5.0,NaN,4.080654e+07

In [34]:
df = df.reset_index()

In [35]:
df = df.drop(['index'],axis = 1)

In [36]:
df

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3,Population2
0,Adams Village,1861.0,0.0,0.0,NaN,0.0,0.0,0.0,12.0,2.0,10.0,0.0,0.0,3.463321e+06
1,Addison Town and Village,2577.0,3.0,0.0,NaN,0.0,0.0,3.0,24.0,3.0,20.0,1.0,0.0,6.640929e+06
2,Akron Village,2846.0,3.0,0.0,NaN,0.0,0.0,3.0,16.0,1.0,15.0,0.0,0.0,8.099716e+06
3,Albany,97956.0,791.0,8.0,NaN,30.0,227.0,526.0,4090.0,705.0,3243.0,142.0,NaN,9.595378e+09
4,Albion Village,6388.0,23.0,0.0,NaN,3.0,4.0,16.0,223.0,53.0,165.0,5.0,NaN,4.080654e+07
5,Alfred Village,4089.0,5.0,0.0,NaN,0.0,3.0,2.0,46.0,10.0,36.0,0.0,NaN,1.671992e+07
6,Allegany Village,1781.0,3.0,0.0,NaN,0.0,0.0,3.0,10.0,0.0,10.0,0.0,0.0,3.171961e+06
7,Amherst Town,118296.0,107.0,1.0,NaN,7.0,31.0,68.0,2118.0,204.0,1882.0,32.0,3.0,1.399394e+10
8,Amityville Village,9519.0,9.0,0.0,NaN,2.0,4.0,3.0,210.0,16.0,188.0,6.0,1.0,9.061136e+07
9,Amsterdam,18182.0,30.0,0.0,NaN,0.0,12.0,18.0,405.0,99.0,291.0,15.0,0.0,3.305851e+08
10,Arcade Village,2053.0,0.0,0.0,NaN,0.0,0.0,0.0,39.0,3.0,35.0,1.0,0.0,4.214809e+06
11,Ardsley Village,4523.0,5.0,0.0,NaN,0.0,3.0,2.0,33.0,4.0,28.0,1.0,0.0,2.045753e+07
12,Asharoken Village,658.0,0.0,0.0,NaN,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,4.329640e+05
13,Attica Village,2522.0,2.0,0.0,NaN,0.0,0.0,2.0,5.0,0.0,4.0,1.0,0.0,6.360484e+06
14,Auburn,27270.0,96.0,1.0,NaN,20.0,22.0,53.0,859.0,132.0,721.0,6.0,NaN,7.436529e+08
15,Avon Village,3333.0,1.0,0.0,NaN,0.0,1.0,0.0,25.0,3.0,20.0,2.0,NaN,1.110889e+07
16,Baldwinsville Village,7473.0,5.0,0.0,NaN,0.0,1.0,4.0,88.0,10.0,77.0,1.0,0.0,5.584573e+07
17,Ballston Spa Village,5418.0,8.0,0.0,NaN,0.0,3.0,5.0,94.0,16.0,78.0,0.0,1.0,2.935472e+07
18,Batavia,15374.0,57.0,0.0,NaN,7.0,13.0,37.0,559.0,103.0,454.0,2.0,NaN,2.363599e+08
19,Bath Village,5733.0,15.0,0.0,NaN,1.0,3.0,11.0,191.0,32.0,157.0,2.0,2.0,3.286729e+07
20,Bedford Town,17627.0,5.0,0.0,NaN,0.0,1.0,4.0,156.0,26.0,127.0,3.0,NaN,3.107111e+08
21,Bethlehem Town,34243.0,13.0,0.0,NaN,0.0,3.0,10.0,442.0,50.0,388.0,4.0,NaN,1.172583e+09
22,Binghamton,46304.0,284.0,3.0,NaN,19.0,101.0,161.0,2349.0,525.0,1767.0,57.0,NaN,2.144060e+09
23,Black River,1410.0,0.0,0.0,NaN,0.0,0.0,0.0,14.0,2.0,12.0,0.0,0.0,1.988100e+06
24,Blooming Grove Town,12001.0,8.0,0.0,NaN,1.0,0.0,7.0,99.0,20.0,72.0,7.0,NaN,1.440240e+08
25,Bolivar Village,1022.0,1.0,0.0,NaN,0.0,0.0,1.0,4.0,2.0,2.0,0.0,0.0,1.044484e+06
26,Bolton Town,2325.0,2.0,0.0,NaN,0.0,0.0,2.0,24.0,4.0,20.0,0.0,0.0,5.405625e+06
27,Boonville Village,2054.0,1.0,0.0,NaN,0.0,0.0,1.0,20.0,6.0,14.0,0.0,0.0,4.218916e+06
28,Brant Town,2065.0,4.0,0.0,NaN,0.0,1.0,3.0,31.0,9.0,20.0,2.0,0.0,4.264225e+06
29,Brewster,2358.0,0.0,0.0,NaN,0.0,0.0,0.0,13.0,3.0,10.0,0.0,0.0,5.560164e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,Utica,61686.0,361.0,7.0,NaN,27.0,102.0,225.0,2528.0,449.0,1997.0,82.0,NaN,3.805163e+09
322,Vestal Town,27980.0,16.0,0.0,NaN,2.0,6.0,8.0,571.0,39.0,523.0,9.0,NaN,7.828804e+08
323,Walden Village,6887.0,18.0,1.0,NaN,2.0,1.0,14.0,142.0,13.0,124.0,5.0,NaN,4.743077e+07
324,Wallkill Town,27940.0,40.0,0.0,NaN,3.0,16.0,21.0,767.0,91.0,650.0,26.0,1.0,7.806436e+08
325,Walton Village,3012.0,6.0,0.0,NaN,1.0,0.0,5.0,68.0,18.0,50.0,0.0,NaN,9.072144e+06
326,Warsaw Village,3453.0,6.0,0.0,NaN,1.0,0.0,5.0,78.0,5.0,73.0,0.0,0.0,1.192321e+07
327,Washingtonville Village,5828.0,2.0,0.0,NaN,0.0,1.0,1.0,58.0,5.0,51.0,2.0,0.0,3.396558e+07
328,Waterford Town and Village,8392.0,4.0,0.0,NaN,0.0,0.0,4.0,59.0,6.0,52.0,1.0,0.0,7.042566e+07
329,Waterloo Village,5175.0,11.0,0.0,NaN,0.0,3.0,8.0,194.0,23.0,169.0,2.0,NaN,2.678062e+07
330,Watertown,28179.0,109.0,0.0,NaN,12.0,16.0,81.0,1165.0,169.0,953.0,43.0,NaN,7.940560e+08
331,Watervliet,10245.0,26.0,1.0,NaN,3.0,11.0,11.0,242.0,58.0,163.0,21.0,NaN,1.049600e+08
332,Watkins Glen Village,1862.0,6.0,0.0,NaN,0.0,0.0,6.0,92.0,10.0,80.0,2.0,NaN,3.467044e+06
333,Waverly Village,4337.0,5.0,0.0,NaN,0.0,1.0,4.0,54.0,9.0,41.0,4.0,NaN,1.880957e+07
334,Webster Town and Village,43777.0,21.0,0.0,NaN,2.0,3.0,16.0,469.0,101.0,361.0,7.0,NaN,1.916426e+09
335,Weedsport Village,1797.0,0.0,0.0,NaN,0.0,0.0,0.0,25.0,5.0,20.0,0.0,0.0,3.229209e+06
336,Wellsville Village,4574.0,11.0,0.0,NaN,1.0,0.0,10.0,164.0,32.0,129.0,3.0,1.0,2.092148e+07
337,Westhampton Beach Village,1732.0,2.0,0.0,NaN,0.0,0.0,2.0,44.0,4.0,37.0,3.0,0.0,2.999824e+06
338,West Seneca Town,44821.0,35.0,1.0,NaN,1.0,9.0,24.0,896.0,166.0,710.0,20.0,0.0,2.008922e+09
339,Whitehall Village,2604.0,6.0,0.0,NaN,0.0,0.0,6.0,62.0,12.0,49.0,1.0,NaN,6.780816e+06
340,White Plains,57559.0,78.0,1.0,NaN,3.0,28.0,46.0,1232.0,77.0,1134.0,21.0,NaN,3.313038e+09
341,Whitesboro Village,3733.0,4.0,0.0,NaN,0.0,0.0,4.0,36.0,14.0,21.0,1.0,0.0,1.393529e+07
342,Whitestown Town,9141.0,0.0,0.0,NaN,0.0,0.0,0.0,77.0,13.0,61.0,3.0,0.0,8.355788e+07
343,Woodbury Town,10685.0,3.0,0.0,NaN,0.0,2.0,1.0,541.0,9.0,529.0,3.0,NaN,1.141692e+08
344,Woodridge Village,829.0,7.0,0.0,NaN,0.0,0.0,7.0,17.0,8.0,9.0,0.0,0.0,6.872410e+05
345,Woodstock Town,5931.0,2.0,0.0,NaN,0.0,0.0,2.0,58.0,13.0,45.0,0.0,NaN,3.517676e+07
346,Yonkers,199134.0,1036.0,6.0,NaN,25.0,390.0,615.0,2368.0,470.0,1662.0,236.0,10.0,3.965435e+10
347,Yorktown Town,36643.0,15.0,0.0,NaN,0.0,2.0,13.0,334.0,45.0,287.0,2.0,NaN,1.342709e+09
348,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN